### ISSUE TITLE
[Bugfix] - After add i18n, build stops to work

### ISSUE THREAD

**Issue by raulfdm** [raulfdm/site#32]
Run locally it works fine, however, when we try to build, it throws:

```bash
 Building static HTML for pagesReferenceError: XMLHttpRequest is not defined
    at Object.ajax (/Users/raulmelo/projects/personal/site/public/render-page.js:32335:5)
    at Backend.loadUrl (/Users/raulmelo/projects/personal/site/public/render-page.js:32459:20)
    at Backend.read (/Users/raulmelo/projects/personal/site/public/render-page.js:32452:12)
    at Connector.read (/Users/raulmelo/projects/personal/site/public/render-page.js:32748:34)
    at Connector.loadOne (/Users/raulmelo/projects/personal/site/public/render-page.js:32814:12)
    at /Users/raulmelo/projects/personal/site/public/render-page.js:32787:16
    at Array.forEach (<anonymous>)
    at Connector.prepareLoading (/Users/raulmelo/projects/personal/site/public/render-page.js:32786:21)
    at Connector.load (/Users/raulmelo/projects/personal/site/public/render-page.js:32793:12)
    at I18n.loadResources (/Users/raulmelo/projects/personal/site/public/render-page.js:34527:40)
    at I18n.loadNamespaces (/Users/raulmelo/projects/personal/site/public/render-page.js:34688:12)
    at loadNamespaces (/Users/raulmelo/projects/personal/site/public/render-page.js:42547:8)
    at /Users/raulmelo/projects/personal/site/public/render-page.js:42492:66
    at new Promise (<anonymous>)
    at useTranslation (/Users/raulmelo/projects/personal/site/public/render-page.js:42491:9)
    at BlogPostTemplate (/Users/raulmelo/projects/personal/site/public/render-page.js:55504:93)
ReferenceError: XMLHttpRequest is not defined
    at Object.ajax (/Users/raulmelo/projects/personal/site/public/render-page.js:32335:5)
    at Backend.loadUrl (/Users/raulmelo/projects/personal/site/public/render-page.js:32459:20)
    at Backend.read (/Users/raulmelo/projects/personal/site/public/render-page.js:32452:12)
    at Connector.read (/Users/raulmelo/projects/personal/site/public/render-page.js:32748:34)
    at Connector.loadOne (/Users/raulmelo/projects/personal/site/public/render-page.js:32814:12)
    at /Users/raulmelo/projects/personal/site/public/render-page.js:32787:16
    at Array.forEach (<anonymous>)
    at Connector.prepareLoading (/Users/raulmelo/projects/personal/site/public/render-page.js:32786:21)
    at Connector.load (/Users/raulmelo/projects/personal/site/public/render-page.js:32793:12)
    at I18n.loadResources (/Users/raulmelo/projects/personal/site/public/render-page.js:34527:40)
    at I18n.loadNamespaces (/Users/raulmelo/projects/personal/site/public/render-page.js:34688:12)
    at loadNamespaces (/Users/raulmelo/projects/personal/site/public/render-page.js:42547:8)
    at /Users/raulmelo/projects/personal/site/public/render-page.js:42492:66
    at new Promise (<anonymous>)
    at useTranslation (/Users/raulmelo/projects/personal/site/public/render-page.js:42491:9)
    at BlogPostTemplate (/Users/raulmelo/projects/personal/site/public/render-page.js:55504:93)
error UNHANDLED EXCEPTION
```

After some investigation, I've realized it's caused by `i18next-xhr-backend` try to fetch all locales via http request and at this moment we don't have either a http server running and `XMLHttpRequest` is not available through this usage.

**Comment by raulfdm** [comment]
## References:

### Starter
- [Post initially used as reference](https://www.gatsbyjs.org/blog/2017-10-17-building-i18n-with-gatsby/) 
- [Note from `i18next-xhr-backend`](https://github.com/i18next/i18next-xhr-backend#misc)
- [Exact same Issue reported at Gatsby Repo](https://github.com/i18next/i18next-xhr-backend/issues/281)

### Possible fixes
- [Plugin to solve this issue](https://github.com/angeloocana/gatsby-plugin-i18n)
- [Long issue discussing many ways to solve that](https://github.com/gatsbyjs/gatsby/issues/3853);
- [Gist (weird) explaining how to do that](https://gist.github.com/acewf/e7f183a0cbc38b6dcd6581bdc10ed9ee);
- [Boilerplate for SSR + i18n - Gatsby V2](https://github.com/guibulator/gatsby-starter-i18next-ssr);
